pipeline:
  build:
    image: plugins/docker
    settings:
      repo: ${CI_REPO}
      tags: latest
      platforms: linux/amd64,linux/arm64
    secrets: [ docker_username, docker_password ]
when:
  branch: master
  event: push
