pipeline:
  lint:
    image: node:20-alpine
    commands:
      - apk --no-cache add git openssh
      - npm ci
      - npm run lint:js
  build:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: ${CI_REPO}
      dry_run: true
when:
  event:
    - pull_request
